# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# example taken from https://github.com/PredictiveEcology/SpaDES/blob/master/.travis.yml
edge: true
sudo: required

language: r


matrix:
  include:

  - os: linux
    dist: precise
    r: oldrel
    cran: http://cran.rstudio.com/
    before_install:
    - tlmgr install xcolor
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

  - os: linux
    dist: precise
    r: release
    cran: http://cran.rstudio.com/
    before_install:
    - tlmgr install xcolor
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start


  - os: linux
    dist: precise
    r: devel
    cran: http://cran.rstudio.com/
    before_install:
    - tlmgr install xcolor
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

  - os: linux
    dist: trusty
    cran: https://cran.rstudio.com/
    before_install:
    - tlmgr install xcolor
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start


  - os: osx
    osx_image: xcode8.2
    cran: https://cran.rstudio.com/
    latex: false
    r_build_args: '--no-build-vignettes --resave-data'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'


r_build_args: "--resave-data"

r_check_args: "--as-cran"

warnings_are_errors: true


branches:
  only:
    - master

